export default {
  author: "Autor(a)",
  readMore: "Ler mais",
  readLess: "Mostrar menos",
  spoilerWarning: "⚠ Contém spoiler ⚠",
  spoilerWarningSecondary: "Clique para ler",
  emailOrUsernamePlaceholder: "E-mail ou nome de usuário",
  passwordPlaceholder: "Senha",
  forgotPassword: "Esqueceu a senha?",
  fullNamePlaceholder: "Nome Completo",
  usernamePlaceholder: "Nome de usuário",
  emailPlaceholder: "E-mail",
  confirmPasswordPlaceholder: "Confirmar senha",
  cancel: "Cancelar",
  post: "Publicar",
  placeholderReview:"Algo a falar sobre seu livro ?",
  genreTitle: "Escolha seus favoritos",
  save: "Salvar",
  review:"Resenha",
  spoilerWarningPlain: "Contém spoiler",
  selectBook: "Selecionar um livro"
};
