export default {
  author: "Autor(a)",
  readMore: "Ler mais",
  readLess: "Mostrar menos",
  spoilerWarning: "⚠ Contém spoiler ⚠",
  spoilerWarningSecondary: "Clique para ler",
  emailOrUsernamePlaceholder: "E-mail ou nome de usuário",
  passwordPlaceholder: "Senha",
  forgotPassword: "Esqueceu a senha?",
  fullNamePlaceholder: "Nome Completo",
  usernamePlaceholder: "Nome de usuário",
  emailPlaceholder: "E-mail",
  confirmPasswordPlaceholder: "Confirmar senha",
  cancel: "Cancelar",
  post: "Publicar",
  namePlaceholder: "Nome",
  bioPlaceholder: "Biografia",
  saving: "Salvando...",
  save: "Salvar",
  errorTitle: "Erro",
  tokenNotFound: "Token de autenticação não encontrado.",
  warningTitle: "Aviso",
  noChangesDetected: "Nenhuma alteração detectada.",
  unexpectedError: "Erro inesperado.",
};
